### PR TITLE
Add candy buttons (with sparkle)

### PR DESCRIPTION
**Pull request by bunnymatic**
Here's the Candy Button treatment (without losing the sparkle).

The css and 1 image file are added under `vendor/assets/{stylesheets,images}` respectively.

In the index page, we choose randomly a shape class and color class and icon to render the buttons.

For more class options, check out the examples on http://simurai.com/archive/buttons/ (the page from which this was stolen)

screen shot 2017-02-04 at 4 11 59 pm

I don't really expect this to get merged, but it's a starting point for candy buttons if you wanted them.

### CODE REVIEW

**Comment by shannonwells** [comment]
Current plan is to merge this (with any desired tweaks) after permalinks.

**Comment by bunnymatic** [comment]
Sadly i'm having issues running tests with the new feature spec stuff...

screen shot 2017-02-14 at 12 24 58 am

```
  14) Clickbait Generator when I visit the home page when I click on a button behaves like a Clickbait Generator page lets me share the headline to Twitter
      Failure/Error: visit '/'

      Selenium::WebDriver::Error::UnknownError:
        Missing 'marionetteProtocol' field in handshake
      Shared Example Group: "a Clickbait Generator page" called from ./spec/features/clickbaits_spec.rb:61
      # ./spec/features/clickbaits_spec.rb:34:in `block (3 levels) in <top (required)>'
```

i'll look into it.

**Comment by bunnymatic** [comment]
Got it - old version of firefox (42.0).  upgrade to 51 got the tests rolling

**Comment by bunnymatic** [comment]
Just rebased on the latest master.  should be ready to roll once you take a look see

**Comment by shannonwells** [comment]
D'oh!

**Comment by bunnymatic** [comment]
here are current screenshots from that branch (on my dev box)

screen shot 2017-02-16 at 9 07 52 pm
screen shot 2017-02-16 at 9 07 46 pm
screen shot 2017-02-16 at 9 07 35 pm
screen shot 2017-02-16 at 9 07 27 pm

**Comment by bunnymatic** [comment]
my bad on the force push.

This last commit is on top of your font and shape mods.  Added new icons that are tied to the different list icon types.  and added sparkles to the permalink share button

**Comment by bunnymatic** [comment]
Just doing a little research - on my machine, changing the icon font to sans-serif makes the smiley face crappy and doesn't change the colored icons at all (the sand timer and the skull).  i wonder if we need a proper icon font to be available to the app.  or we make custom fonts with icomoon...

**Comment by bunnymatic** [comment]
also - i don't (think I) see the offset sparkley issue on this branch.  unless i'm missing something

**Comment by shannonwells** [comment]
ok, if you can please double check that the sparkley offset isn't happening, and merge if it's not, and fix & merge if it is, then let's not make any further changes. We (or I) can figure out the font to use in another branch/PR.  bitmoji

**Comment by bunnymatic** [comment]
fair 'nuf.

i'll double triple check

**Comment by bunnymatic** [comment]
double checked with local instance on Firefox/Safari/Chrome.  They all  looked fine to me.  so i merged.

**Pull request merged**
